using UnityEngine;

public class SlashAtaque : MonoBehaviour
{
    [Header("Configuraci칩n")]
    public float duracion = 0.2f;   // Duraci칩n del tajo
    public int damage = 10; // Esta es tu variable de da침o

    public void ConfigurarArma(int danioPorNivel) 
    {
        damage = danioPorNivel; 
    }   

    void Start()
    {
        // El tajo desaparece r치pido
        Destroy(gameObject, duracion);
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Enemy"))
        {
            var enemigo = other.GetComponent<EnemyControler>();
            
            if (enemigo != null)
            {
                // Usamos la variable 'damage' que ya fue actualizada por el lanzador
                enemigo.Recibirdano(damage);
            }
        }
    }
}
